# Don't print a new line at the start of the prompt
# add_newline = false

# Make the prompt a single line instead of two lines
[line_break]
disabled = true

[character]
success_symbol = '[\[I\] ➜](bold green)'
vimcmd_symbol = '[\[N\] ➜](bold green)'
# These don't work in zsh yet, but maybe one day they will.
# https://github.com/starship/starship/issues/625#issuecomment-732454148
vimcmd_replace_one_symbol = '[\[R\] ➜](bold green)'
vimcmd_replace_symbol = '[\[R\] ➜](bold green)'
vimcmd_visual_symbol = '[V]](bold green)'
