set -o vi

# Interactive shell configuration
eval "$(starship init zsh)"

# tmux-sessionizer
bindkey -s ^f "tmux-sessionizer\n"

# Rename tmux window when running codex
codex() {
  if [ -n "$TMUX" ]; then
    tmux rename-window codex
  fi
  command codex "$@"
}

# Aliases
alias python=python3
alias pyc='py_check'
alias gc='git_cleanup'
# Shortcuts
alias vim='nvim'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../../'
alias .....='cd ../../../../'
alias l='ls -lhF -G'
alias la='ls -lahF -G'
alias grep='grep --color=auto '
alias rg='rg -p '
alias mv='mv -i'
alias cp='cp -i'
alias cwd='pwd | tr -d "\r\n" | pbcopy'

# zsh auto-completion system - point to dotfiles zfunc
fpath+="$HOME/.dotfiles/zfunc"
autoload -Uz compinit; compinit
zstyle ':completion:*' menu select

# Autoload all custom functions
autoload -Uz create_wt cleanup_wt list_worktrees switch_worktree venv py_check git_cleanup azconnect
